#!/usr/bin/env python


import threading
import subprocess
import pipes

outpath = '{0}/{1}'.format('~/octjdl', 'testjp.rar')
url = "http://prx-157.keep2share.cc/086c8fc3db790/6fbecea47e4da/1927b1215dcf9?temp_url_sig=1c608bd36374bfd696bfda2a4ee1bdd0a0239d4eef22c9ad3413d86623821c4090b3876d4142d242b86e57520fb4d922b7ae29d83b4bc2c2f87f35206e414696&temp_url_expires=1475622069&id=c38496f0a4609&node_id=157&project=moneyplatform&user_id=19102&name=SHI004.avi"
proc = subprocess.Popen(
    ['./axel_util', outpath, url],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    shell=False
)
(out, err) = proc.communicate() # Communicate blocks
print 'OUT', out
print 'ERR', err

# print 'axel -o {0} -n4 \\"{1}\\"'.format(outopt, url)

# proc = subprocess.Popen(
#     'axel -o {0} -n4 \\"{1}'.format(outopt, url),
#     stdout=subprocess.PIPE,
#     shell=True
# )
# (out, err) = proc.communicate() # Communicate blocks
# print out
